// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRy7qocei43jWn-JaryoFcGmndSDw_z5Y',
    appId: '1:986159416706:web:0c865dbd1b4bb7845b3b9b',
    messagingSenderId: '986159416706',
    projectId: 'qwiz-fbe62',
    authDomain: 'qwiz-fbe62.firebaseapp.com',
    storageBucket: 'qwiz-fbe62.appspot.com',
    measurementId: 'G-JB9G4P7RL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL524hcSvZtNOodh5y1qEA6pxcf-Tyrkc',
    appId: '1:986159416706:android:fdca7a055dc8a4ac5b3b9b',
    messagingSenderId: '986159416706',
    projectId: 'qwiz-fbe62',
    storageBucket: 'qwiz-fbe62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv11V3b1fWiU_Y4ulRaq8onIddDsFm4R4',
    appId: '1:986159416706:ios:783a791136b7fb755b3b9b',
    messagingSenderId: '986159416706',
    projectId: 'qwiz-fbe62',
    storageBucket: 'qwiz-fbe62.appspot.com',
    iosClientId: '986159416706-eonhkvr0ljtdjso5u3g3981c28m71ibj.apps.googleusercontent.com',
    iosBundleId: 'com.example.formApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv11V3b1fWiU_Y4ulRaq8onIddDsFm4R4',
    appId: '1:986159416706:ios:783a791136b7fb755b3b9b',
    messagingSenderId: '986159416706',
    projectId: 'qwiz-fbe62',
    storageBucket: 'qwiz-fbe62.appspot.com',
    iosClientId: '986159416706-eonhkvr0ljtdjso5u3g3981c28m71ibj.apps.googleusercontent.com',
    iosBundleId: 'com.example.formApp',
  );
}
